### ISSUE TITLE
continuous integration environment

### ISSUE THREAD

**Issue by ycfreeman** [QUT-IFN660-ECMAScript/Native-ECMAScript#1]
connection to travis ci

create travis.yml config file to make the ci platform do
- install appropriate build tools
- install / build tools
- run unit tests

what else?

**Comment by hscells** [comment]
I'm not sure this is crucial right now, considering we only have a basic scanner. I would consider looking at this within the coming weeks.

**Comment by ycfreeman** [comment]
completed at #10
