### ISSUE TITLE
setup tests

### ISSUE THREAD

**Issue by ycfreeman** [QUT-IFN660-ECMAScript/Native-ECMAScript#2]
https://sourceforge.net/projects/cppunit/

do we need a framework or can we do unit tests without a framework?

**Comment by hscells** [comment]
If you have experience with a particular tool, that would be great. I think using a framework is ideal.

**Comment by ycfreeman** [comment]
wayne suggested us not need to go too far on unit testing, but can simply test with diff tests
so here's an example for that
https://github.com/jonathan-beard/simple_wc_example
