### ISSUE TITLE
create tests and expected outputs for lexical analyser

### ISSUE THREAD

**Issue by ycfreeman** [QUT-IFN660-ECMAScript/Native-ECMAScript#21]
create tests (js files)
---
so that we can use these tests to do TDD

acceptance criteria:
1. please put your test files in tests/lex/test
2. expected output in tests/lex/assert
3. create at least 2 test cases
4. each test must include at least 2 not yet tested language features / tokens
5. 1 small test case (2-5 lines), 1 large test case (at least 10 lines)
6. test js files must be valid (try running in browser console)

extend grammar
---
extend grammar.l and grammar.y if needed, test_lex.c as well
so that it can parse your own tests

acceptance criteria:
1. main program must still build
2. test_lex must still build
3. tests must pass "make test"

**Comment by ycfreeman** [comment]
@AnthonyGough @farukbaig @HarjotKaur @jordanhennell @hscells @kojiagile @ksulinski @luantrongtran

**Comment by hscells** [comment]
Can this be closed now?

**Comment by AnthonyGough** [comment]
Added this issue to the Wiki so guidelines outlined - closed issue
