### ISSUE TITLE
Makefile bugs

### ISSUE THREAD

**Issue by ycfreeman** [QUT-IFN660-ECMAScript/Native-ECMAScript#40]
- get an error when I make: `no matches found: grammar.tab.*` I didn’t make before that so it can’t clean
- VAR gets created if tests fail, maybe its doing “something something > VAR, and gets interpreted by shell

**Comment by ycfreeman** [comment]
@hscells hmm there should be a -f for all rm commands, how do you get that error message?

**Comment by hscells** [comment]
Well I'm running zsh, do you think that could be a problem?

**Comment by ycfreeman** [comment]
@hscells it could be, i just use bash flags, seems working fine on shell, does rm -f works on zsh?
