### ISSUE TITLE
Multi-line strings should be able to be empty

### ISSUE THREAD

**Issue by hscells** [QUT-IFN660-ECMAScript/Native-ECMAScript#46]
It looks like modifying https://github.com/QUT-IFN660-ECMAScript/Native-ECMAScript/blob/develop/grammar.l#L151 to make the newline optional will fix the error people are having with multiline strings.

**Comment by ycfreeman** [comment]
seems the issue is fixed after upgrading the compiler? @AnthonyGough

**Comment by AnthonyGough** [comment]
We should be able to close this - all Mac users have no issue and Ubuntu users have upgraded compiler so this issue no longer exists - recommend close issue

**Comment by ycfreeman** [comment]
closing this
