### ISSUE TITLE
Identify shift/reduce conflicts

### ISSUE THREAD

**Issue by AnthonyGough** [QUT-IFN660-ECMAScript/Native-ECMAScript#56]
**bison --verbose grammar.y**

Will produce grammar.output to show unused/useless tokens, nonterminals but more imp the automaton state transitions - so currently the shift reduce conflicts can visualise the states which have conflicts
e.g.

- State 51 conflicts: 4 reduce/reduce
- State 60 conflicts: 4 reduce/reduce
- State 110 conflicts: 2 reduce/reduce

Sample grammar.output in branch anthony or generate yourself - added to .gitignore

**Comment by hscells** [comment]
See #65
