### ISSUE TITLE
error messages with newlines

### ISSUE THREAD

**Issue by ycfreeman** [QUT-IFN660-ECMAScript/Native-ECMAScript#58]
researched on it these few days, it's apparently very difficult, as gnumake simply doesn't play well with newlines.
- $(shell) strips out newlines
- $(error),$(warning) etc doesn't treat \n as newlines

there could be ways like reading the file in a way that $(foreach) can read it as multiple lines, then do echo for each line, but its just wasting time

may not look into it again, so marking it as enhancement

**Comment by hscells** [comment]
is this for flex? If you checkout my branch, I've managed to write custom error messages with c++ classes.

**Comment by ycfreeman** [comment]
i'm just trying to write all stderror to log.txt, then use $(error) in Makefile to print out the contents,
then just remove the file after everything is done,

i'll keep just the log.txt file for human read for now
