### ISSUE TITLE
Fix failing tests

### ISSUE THREAD

**Issue by hscells** [QUT-IFN660-ECMAScript/Native-ECMAScript#66]
After porting code to c++ some tests are failing when lexing

**Comment by ycfreeman** [comment]
```
yyFlexLexer* lexer = new yyFlexLexer();
token = lexer->yylex();
```

it can build but its not reading the file
thats why its throwing that many diff errors all with “<“, because the log.txt it splits out contains nothing in it

**Comment by ycfreeman** [comment]
we're going back to c for lexer, closing this
